### PR TITLE
task5

### PR DESCRIPTION
**Pull request by OleksandrShevchukKI**

### CODE REVIEW

**Review by PavloFedakNULP — CHANGES_REQUESTED** [review]
Please add screen with % of coverage by tests

**Comment by OleksandrShevchukKI** [comment]
> Please add screen with % of coverage by tests

Added a screenshot with test coverage to the Readme.
The low percentage of test coverage is due to the fact that many private methods were used for initialization, loading configurations, and using the SerialPort class.

**Comment by PavloFedakNULP** [comment]
Have you looked into how to mark private methods to cover them with tests?

**Comment by OleksandrShevchukKI** [comment]
> Have you looked into how to mark private methods to cover them with tests?

So I read about reflection, which allows you to access private methods.
However, using reflection in tests contradicts protected languages, including C#, because we lose performance, type safety, etc.
Reflection is a great tool, but not for tests.

**Review by PavloFedakNULP — APPROVED** [review]

**Pull request merged**
